### ISSUE TITLE
Map to Gartner DevSecOps model

### ISSUE THREAD

**Issue by louwersj** [devsecopsmaturitymodel/DevSecOps-MaturityModel#14]
Gartner has build their view on DevSecOps, and value can be found in what they have created. 

[https://www.techwire.net/sponsored/integrating-security-into-the-devsecops-toolchain.html](https://www.techwire.net/sponsored/integrating-security-into-the-devsecops-toolchain.html)

![](https://media.erepublic.com/image/gartner-graphic.png)

The flow, as outlined by gartner, has the following stages:

- Plan
- Create
- Verify
- Preprod
- Release
- Prevent
- Detect
- Respond
- Predict
- Adapt

I think, it would add value if we can map the dimensions of the maturity model in some way or form to the stages from the DevSecOps toolchain/pipeline/process as outlined by the people from Gartner. This would help people to plot what needs to be done where and to outline how mature they are in which area of the DevSecOps toolchain/pipeline/process.

In addition, this ensures we have a view for people with a tech background as well as for the more (senior)management side of a company. Both can obtain the level of understanding they need in a way they can relate to.

**Comment by wurstbrot** [comment]
Indeed, I think that infinity loop is the standard DevOps visualization today.

I am not sure that it should be mapped to the specific "Gartner" one with 10 phases.
I like the more generic (non comercial) one with 8 phases more:
- Plan
- Code
- Build
- Test
- Release
- Deploy
- Operate
- Measure

I could implement a "DevOpsChain" Attribute and we just need to map the phases, same like for SAMM. This way, we will identity missing activities.

What do you think about cutting it down?

**Comment by louwersj** [comment]
I do agree. In all honesty,... I do not really really see the added value in the model created by Gartner and it carries some additional things in it that are not standard in the way people tend to look at this.

![](https://miro.medium.com/max/1400/1*AwvDJDfErlD34ox2QpwGoA.png)

The default model (as shown) makes a lot more sense compared to the Gartner model. So,.. yes... let's go for the standard model. The downside, which we have to balance, is that in general Gartner is seen at some levels in enterprises as having a high level of truth to it (which is debatable on a case per case basis). 

By not adopting the Gartner model we run into the risk that some levels in an enterprise might see this as a lack in our maturity model. As with every risk,... we have to mitigate it, and to mitigate it I would like to propose the following:

we use the 8 phase model and map this to the maturity model and add a "DevOpsChain" attribute.
I will write a short piece as additional information where we outline the 8 phase model which is used in the maturity model and how this aps to the 10 phase model of Gartner. 

By doing so we keep the maturity model clean and in line with the 8 phase model while we also satisfy people who have a quistion on how this relates to the 10 phase model from gartner. 

Would that work for you?

If you can add the "DevOpsChain" attribute I will write a short text to be included in the content of the page as an explanatory section.

**Comment by wurstbrot** [comment]
I want to bring to picture also, that DevOps often is used with:
- Culture
- Processes 
- Architecture
- Automation & Measures

One of many sources: Guide to Implementing DevSecOps for a
System of Systems in Highly Regulated
Environments, https://resources.sei.cmu.edu/asset_files/TechnicalReport/2020_005_001_638589.pdf (Page 1)

Due to even less dimensions (4) I am not saying that it must be like that, is more related to the target `In addition, this ensures we have a view for people with a tech background as well as for the more (senior)management side of a company. Both can obtain the level of understanding they need in a way they can relate to.`

In the DevOps toolchain, my main concern is to fit culture related activities.

**Comment by wurstbrot** [comment]
This research is more about the chain https://www.lean-security.org/
