### ISSUE TITLE
Re-assess the security of TOTP vs other mechanisms

### ISSUE THREAD

**Issue by ioggstream** [devsecopsmaturitymodel/DevSecOps-MaturityModel#160]
## Task

- reassess the security of TOTP vs other mechanisms like security keys

**Comment by wurstbrot** [comment]
Hi @ioggstream !
Currently, the following is listed for 2FA:
      - $ref: src/assets/YAML/default/implementations.yaml#/implementations/smartcard
      - $ref: src/assets/YAML/default/implementations.yaml#/implementations/yubikey
      - $ref: src/assets/YAML/default/implementations.yaml#/implementations/sms
      - $ref: src/assets/YAML/default/implementations.yaml#/implementations/totp
      
What else would you add, FIDO?
