### ISSUE TITLE
Comprehensive activity view

### ISSUE THREAD

**Issue by ioggstream** [devsecopsmaturitymodel/DevSecOps-MaturityModel#192]
##  I expect

A comprehensive activity view

![image](https://user-images.githubusercontent.com/1140844/205974573-cd36dd9b-77f8-4655-8f97-39c563a7f566.png)

**Comment by ioggstream** [comment]
Hi @0x41head and @wurstbrot. WDYT about this kind of panel? The current behavior (click on Activity changes webpage) is not very intuitive to me :)

**Comment by 0x41head** [comment]
Hey @ioggstream,
I think the idea is great but might be difficult to implement. One of the problems I was facing while creating the circular heatmap was the overlapping of the labels (the ones on the circumference). When two of them overlapped, we could no longer click on any segments inside the circular heatmap. So I had to make the size of the heatmap static. If we were to add the activity description on the left, it would overflow for screen sizes with width less than or equal to (atleast) 1920

**Comment by wurstbrot** [comment]
@0x41head what about under it?

**Comment by 0x41head** [comment]
@wurstbrot that could work.
What do you think @ioggstream ?

**Comment by ioggstream** [comment]
Not sure. What if all the text appear in a separate panel above the heat map? I don't need the heat map to select the activities.

**Comment by 0x41head** [comment]
Do we not allow access to the heatmap after selecting activities ? or do we make some sort of a go back button to return to the heatmap ?

**Comment by ioggstream** [comment]
I think something like `esc` button when you're done clicking. I usually take some minutes before switching between the various heatmap cells.

**Comment by 0x41head** [comment]
I think that can be implemented. I won't be able to pick this up before February though.

**Comment by 0x41head** [comment]
@wurstbrot @ioggstream 
Is this issue still of interest ?

**Comment by wurstbrot** [comment]
yes, please wait for GSOC 2023 before you start implementing. I am not sure if we get a student.

**Comment by akhileshappala** [comment]
Hi @ioggstream and @wurstbrot 
This design looks good. is this something like this
1. When we enter the page - the map will be occupying the full page.
2. When we select a level of a step, it will move a little to the left side with some smooth animation and the internal steps box(Card component)  will come on the top right corner ( But not like the current one, as the map is going down and page is scrolling down)
3. Then when we select any internal step from the card component. The right panel will be coming up with collapse and expansion with smooth animation of the heat map and card sliding to left, 

I have a design idea,
When we select a level of the heat map, we can come up with a popup over there and we can select the internal steps and click on confirm or close to make it close. and when a user wants to see the panel with expand and collapse he can click on the internal step.

 The current one looks good, I am looking forward to implementing it, and dynamically moving the heatmap to the left.

**Comment by akhileshappala** [comment]
Also, we can add Confirm and cancel buttons to the Internal steps(card - with checkboxes) so that we can close it automatically. same for the side panel also.

I see that the green hamburger is moved to the right, which means are we changing the complete menu to the right side.

**Comment by ptechofficial** [comment]
I think we can close this issue now. @wurstbrot @0x41head
