### ISSUE TITLE
ISO 27001:2022 Mapping

### ISSUE THREAD

**Issue by dknomura** [devsecopsmaturitymodel/DevSecOps-MaturityModel#217]
As a compliance engineer, I want to see the DSOMM to ISO 27001:2022 mapping to help maintain/gain ISO 27001 compliance. Mapping ISO 27001:2017 to 2022 can be seen here. https://www.nqa.com/medialibraries/NQA/NQA-Media-Library/PDFs/NQA-ISO-27002-Mapping.pdf

**Comment by wurstbrot** [comment]
implemented
