### ISSUE TITLE
Map with NIST Software Supply Chain and DevOps Security Practices once it is released.

### ISSUE THREAD

**Issue by martinmarsicano** [devsecopsmaturitymodel/DevSecOps-MaturityModel#230]
A NIST DevSecOps guidance project is currently underway. Some months ago I saw a newer draft, but now I can't find it.

Project page: https://www.nccoe.nist.gov/projects/software-supply-chain-and-devops-security-practices

Workshop: https://www.nccoe.nist.gov/get-involved/attend-events/nccoe-devsecops-workshop/overview

Current Draft: https://www.nccoe.nist.gov/sites/default/files/2022-11/dev-sec-ops-project-description-final.pdf

**Comment by wurstbrot** [comment]
Thank you for the hint. So far, we couldn't do it so I close it.
