### ISSUE TITLE
YAML Structure for Team-Based Assessment

### ISSUE THREAD

**Issue by ptechofficial** [devsecopsmaturitymodel/DevSecOps-MaturityModel#237]
For Team-Based Assessment #211 , we need to update YAML structure that can incorporate details of the team that have completed this task.

I was thinking we can do something like this.
This is in "meta.yaml" file.
![image](https://github.com/wurstbrot/DevSecOps-MaturityModel/assets/64535754/fd27c51c-4457-461e-9401-690ea8490588)

And for "generated.yaml" file we can do something like this:
![image](https://github.com/wurstbrot/DevSecOps-MaturityModel/assets/64535754/f25d8984-085d-4627-8269-f727dc470e41)

**Comment by kjartab** [comment]
Having used DSOMM to assess an organization, I'm not convinced this is the right way to go. While you could do this for "team-based activities" it wont cut it for others. Most organizations are complex with many different teams, environments, applications and systems. Examples of granularity:
- Hosting environment: A (on-prem), B (cloud provider 1), C (cloud provider 2)
- Teams in all shapes and sizes
- Different types of systems: Frontend, backend, VM-based, Container-based, Desktop, Mobile - with varying stacks, requirements ++

All these dimensions will "slice up" the activity in ABCs.. Adding "x-implemented" for each new problem will not be very sustainable. I think its better to use a "context" in which you are assessing the different activites - and then aggregate them for whichever view you want to use. 

E.g. DSOMM assessment:
1. Context: Organization:  security training for all employees - true 
2. Context: Environment A: Filter outgoing traffic - true
3. Context: Team 1:  security champion - true
4. Context: Team 2:  security champion - false
5. Context: System C: Coverage of client side dynamic components - true
