### ISSUE TITLE
State or Tag for "Not yet assessed"

### ISSUE THREAD

**Issue by LittlePrimate** [devsecopsmaturitymodel/DevSecOps-MaturityModel#241]
I'd like to throw a possible improvement in here for discussion: differentiation between features that you do not have and features that were not (yet) evaluated.

Currently the only way I see is checking whether you wrote something in e.g. the "Evidence" field, which can make it hard to get started again when you for some reason took a break during you assessment.

Options might be a "todo"-label (which would make the yaml searchable and could be translated into some kind of symbol on the chart - @ptechofficial was thinking about some kind of yellow exclamation mark symbol as a first idea) or simply a third state. I think the third state might make the whole thing more messy, especially because you can no longer simply check the Implementation Chart.
Additional question would be whether this label/state/whatever should then be automatically applied to all categories or if it's something the user has to add manually. In theory starting in "Todo" would actually make sense in my mind because you either want to anyways manually remove levels you do not want to assess or you can leave them in the Todo-state to signal that, while these fields are still white, it does not mean that your team/organisation is not doing this, you actually just never assessed it.

Any thoughts on this?

**Comment by ivareri** [comment]
Having a tri-state (Not assessed, implemented, not implemented) would be useful to keep track of progress. Esp. if you need to pause in the middle of an assessment and return to it days, or weeks, later. 

During some assessments I've also been missing a "Not applicable" state.

**Comment by wurstbrot** [comment]
With the current "tags", you can reach such a status. But to do it is difficult I think because it is not very handy.

**Comment by jdsmithit** [comment]
Hey I also want "Not Applicable" as a state which can be updated in the UI  :D

**Comment by navanhasan** [comment]
ey everyone! This issue on GitHub looks like it was closed because it was inactive for a while. As someone who wants to contribute to the DSOMM Main application for Google Summer of Code (GSOC) in 2025, I'm thinking about adding a new way to track things. I've already made my own copy of this project on GitHub, and I'd be really excited if I got the chance to work on it as a GSOC contributor!
