### ISSUE TITLE
Broken Heatmap on firefox

### ISSUE THREAD

**Issue by 0x41head** [devsecopsmaturitymodel/DevSecOps-MaturityModel#261]
The heatmap on the stable release seems to be broken on Firefox.

![image](https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel/assets/53595853/63a92737-3555-4eea-bfe2-d75dd44335b3)

@wurstbrot if you can confirm this issue, I can start working on it

**Comment by wurstbrot** [comment]
@0x41head I can not confirm, but maybe you have an old stored version in your browser.
See also https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel/pull/262

**Comment by jdsmithit** [comment]
@wurstbrot @0x41head I can confirm this fixed it for me.
