### ISSUE TITLE
Add Title to window tab

### ISSUE THREAD

**Issue by wurstbrot** [devsecopsmaturitymodel/DevSecOps-MaturityModel#268]
Currently the page is not shown in the window tab.
As a user with multiple tabs open, I would like to see which page on dsomm is open in the tab preview.

For the matrix page for example, the title should be "DSOMM - Matrix".

**Comment by nishant2253** [comment]
Hey @wurstbrot, I've successfully addressed this matter on my local server and adhered to the code style outlined in **ESLint.config**. Could you please assign this issue to me? I've also included a screenshot of the updated title for your reference.


![Screenshot from 2024-03-19 14-05-21](https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel/assets/119959229/a6eca490-79b7-4338-92d9-0d935cccd3ff)

**Comment by wurstbrot** [comment]
Cool, where is the PR?

**Comment by nishant2253** [comment]
I'm currently creating a pull request for the modifications for the same.
