### ISSUE TITLE
BUG - Model will not save when you navigate away from Implementations levels to Matrix and back again.

### ISSUE THREAD

**Issue by jdsmithit** [devsecopsmaturitymodel/DevSecOps-MaturityModel#273]
**Prerequisites**

- Local storage Key  = dataset must be set and changed via the heat map.  Example

---------------------------------------------------------

**Reproduction steps** 

1) Navigate too - https://dsomm.owasp.org/circular-heatmap
2) Clear data storage removing Key and Value
3) Check the box for a control, I am selecting 'Education and Guidance' -> 'Ad-Hoc Security training for software developers' for team 'C'.
4) Download the Yaml file by clicking 'Download edited YAML file button' in the bottom right.
5) Search for 'Ad-Hoc Security training for software developers' and you should see the YAML file has a value of true for the 'C' team.
6) Now Click the Burger icon in the top left 'if needed' to get the menu and navigate to Matrix.
7) Once Loaded click Implementations levels to navigate back to the radial graph.
(optional) ensure that Local storage in the browser has a Key  = 'dataset' with 'json' as this must be set and changed via the heat map.
8) Right now if you download the YAML file you will now notice it will no longer download a YAML file with the value of 'Ad-Hoc Security training for software developers' for team 'C' set to True. It will now be false.
9) To confirm this is super broke you can check the box for another control with another team, I am selecting 'Design' -> 'Conduction of simple threat modeling on technical level' for team 'B'.
10) Again download the YAML file and you will notice that the control is also set to false in the YAML.

---------------------------------------------------------

To get it working again you need to remove the browers Local storage, Key & value for 'Dataset'. & reload the page, this looses your previous changes

---------------------------------------------------------

To me, it looks like it is not correctly loading the dataset back into the YamlObject. I am currently trying to find a fix locally.

**Comment by 0x41head** [comment]
Thanks for the PR @jdsmithit
