### ISSUE TITLE
 Overlapping Buttons on Android Screen

### ISSUE THREAD

**Issue by piyushs131** [devsecopsmaturitymodel/DevSecOps-MaturityModel#275]
Issue Description:
After opening the heatmap and going to download the YAML file, I noticed that on the Android screen, the "Download YAML File" button and the "Reset implemented " button are overlapping. This makes it challenging to interact with both buttons effectively, as they interfere with each other functionality.

Steps to Reproduce:
1: Open the heatmap feature.
2: Proceed to download the YAML file.
3: Notice the overlapping of the "Download YAML File" and "Reset" buttons on the Android screen.

Expected Behavior:
The buttons should be displayed in a non-overlapping manner, ensuring that users can easily interact with both without any interference.

![Screenshot 2024-03-07 020649](https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel/assets/140651227/63628c84-f40d-42cc-882f-66c02bdb6b5c)

**Comment by wurstbrot** [comment]
good spot!
