### ISSUE TITLE
Mappings filter missing html li tag

### ISSUE THREAD

**Issue by ethrgeist** [devsecopsmaturitymodel/DevSecOps-MaturityModel#279]
When using the reference filters on `/mapping`, the filtered/sorted items lose their `<li></li>` tag, also there are weird padding spaces and a html comment tag

E.g., a SAMM entry when sorted by activity

```html
<td _ngcontent-nab-c85="" role="cell" mat-cell="" class="mat-cell cdk-cell cdk-column-samm2 mat-column-samm2 ng-star-inserted"><ul _ngcontent-nab-c85=""><li _ngcontent-nab-c85="" class="ng-star-inserted"> I-SB-2-A </li><!----></ul></td>
```

Same entry, when sorted by SAMM
```html
<td _ngcontent-vii-c164="" role="cell" mat-cell="" class="mat-cell cdk-cell cdk-column-samm2 mat-column-samm2 ng-star-inserted">I-SB-2-A</td>
```

**Comment by 0x41head** [comment]
When sorted by activity, a single entry can have multiple SAMM values, hence the need for a list.

![image](https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel/assets/53595853/ac4e3b9c-db97-4b42-9ca4-b947970e5511)
_Single activity, multiple SAMM_ 

When sorted by SAMM, the number of entries are increased, where a single activity is replicated multiple times, with each activity having a single SAMM value. Thus, no need for a list.

![image](https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel/assets/53595853/47aff7fb-ef13-42c3-9220-edd6613d6916)
![image](https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel/assets/53595853/190cf74e-2669-4b1a-ad2b-7cac3f47749b)
_Multiple activity, single SAMM_ 

No, idea why there is so much unnecessary padding though.
