### ISSUE TITLE
Empty dataset ends in mangled heatmap

### ISSUE THREAD

**Issue by ethrgeist** [devsecopsmaturitymodel/DevSecOps-MaturityModel#281]
If one ends up with a empty/corrupted local storage, the heat map does not render.

Besides deleting the local storage through the browser console, there is no reset for it.

The reset implemented button only works if the data set storage is a valid and filled json string.

The reset button should remove or re-initilise the local storage dataset to ensure a working heatmap.

**Comment by jdsmithit** [comment]
Would you want to download the json so you could do a manual merge?  or is this abit over the top?
