### ISSUE TITLE
Download of edited YAML file downloads mounted state instead of edited state from heatmap

### ISSUE THREAD

**Issue by towameister** [devsecopsmaturitymodel/DevSecOps-MaturityModel#286]
I noticed that downloading an edited YAML file sometimes does not reflect new changes made, but instead yields the version which was mounted upon container start. Upon closer examination, I discovered that console logs print two versions of the ALL_CARD_DATA object when refreshing the page (cache disabled), one which contains the mounted state, and one which contains the edited state. For some reason, the corresponding YAML object is not updated properly to represent the state in localStorage when refreshing the page inbetween the edit and download steps. 

Steps to reproduce:

1. Launch via docker, mounting a .yaml file as described in documentation
2. edit heatmap
3. refresh page
4. Download edited YAML file (this YAML file does not reflect changes in UI)

**Comment by Nitwix** [comment]
Not sure if it helps, but apparently the documentation to mount a custom .yaml is wrong. The path of the file in the container is wrong.

For me, the following worked:
`docker run -p 8080:8080 -v /path/to/local/file.yaml:/srv/assets/YAML/generated/generated.yaml wurstbrot/dsomm:latest`

There are also a few parsing errors with the default generated .yaml file (which are shown in the js console when loading the modified file). If you solve them (two errors for the whole file in my case), it seems to work.

**Comment by wurstbrot** [comment]
@Nitwix Are you able to create a PR with the needed changes? Will be happy to merge.

**Comment by Nitwix** [comment]
> @Nitwix Are you able to create a PR with the needed changes? Will be happy to merge.

Done! https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel/pull/298

However, I don't think this completely solve this issue: the generated .yaml file which can be downloaded does indeed not always reflect the modified state of the heatmap, as indicated by @towameister

**Comment by wurstbrot** [comment]
ah, I see, by moving from apache to Caddy the folder has changed. Thank you for the PR.
