### ISSUE TITLE
Question about how to install

### ISSUE THREAD

**Issue by DavidW1519** [devsecopsmaturitymodel/DevSecOps-MaturityModel#301]
hi, im a student that just started to learn about dsomm and i wanted to know what does the teams and group means
![image](https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel/assets/171082546/a884c0bb-9dd0-49b0-aabb-28eaf485553e)
is it just for multiple teams or something else, also if i want to implement it in 1 team how do i edit that so it fits
also is there a step by step guide about how to run that on docker?
i used the docker pull wurstbrot/dsomm:latest && docker run --rm -p 8080:8080 wurstbrot/dsomm:latest but i want to customize it and dont really get the instruction so please any help is welcome thanks in advance

**Comment by wurstbrot** [comment]
Hi @DavidW1519 ,

for customization please take a look at https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel-custom .
For teams https://github.com/devsecopsmaturitymodel/DevSecOps-MaturityModel?tab=readme-ov-file#teams-and-groups
