### ISSUE TITLE
Circular Heat Map Clipped on Website

### ISSUE THREAD

**Issue by enzowritescode** [devsecopsmaturitymodel/DevSecOps-MaturityModel#324]
The circular heat map on the website is not fully visible.

Desktop:
![Desktop view](https://github.com/user-attachments/assets/1e982982-ad26-4058-a3be-74413c0bb324)

Mobile:
![Mobile view](https://github.com/user-attachments/assets/069fe6fc-ea92-462e-80cf-1ba132d8ca75)

**Comment by wurstbrot** [comment]
This is a known bug. Please use the browsers zoom out (e.g. strg and -) feature.

PRs to fix it are welcome.
