### ISSUE TITLE
Matrix view does not show current status

### ISSUE THREAD

**Issue by vbakke** [devsecopsmaturitymodel/DevSecOps-MaturityModel#335]
When I register 'Implemented by' on the heatmap page, the matrix view does not update. It still shows:

```
Implemented By
    B:false
    C:false
    Default:false 
```

**Comment by wurstbrot** [comment]
ImplementedBy is not supported. Please use `teamsImplemented`.

**Comment by vbakke** [comment]
Sorry,  I'm not sure what you mean. I was not using any yaml settings. Using mouse clicks only.

 I ticked off Team B in one of the tasks in heatmap. So I assumed the same box would be ticked off for the same Team when viewed in the grid layout.

Have I misunderstood the concept? Are the not related?

And a second question then is: Is the idea behind the  DSOMM to be interactive user interface,  or is it meant to display data from yaml files? (Which then mus be generated from another system. )

Sorry if I'm completely off the track here. I'm just trying to get the grasp of this. 🙂

Cheers

**Comment by wurstbrot** [comment]
>Sorry, I'm not sure what you mean. I was not using any yaml settings. Using mouse clicks only.
Ah, I see. @0x41head, can you look at it?


> And a second question then is: Is the idea behind the DSOMM to be interactive user interface, or is it meant to display data from yaml files? (Which then mus be generated from another system. )
For "playing" use the UI, otherwise I recommend yaml.

**Comment by 0x41head** [comment]
This bug happens because we are using the local storage for the heatmap and the yaml file for the matrix section. 
Working on a fix rn. Should be done by the end of this month.

**Comment by vbakke** [comment]
_This comment to avoid way too early autoclose_
