### ISSUE TITLE
Team and group names with space fail

### ISSUE THREAD

**Issue by vbakke** [devsecopsmaturitymodel/DevSecOps-MaturityModel#345]
1) Edit team names in 'meta'
    - Rename `Default` to `Team A` in `teams` and `teamGroups`
    - Add `Group B: ['B', 'C']` 

2) Refresh your browser

* The team filters are showing the new names ok (with space)
* Selecting `Team A` has no effect
* *Selecting `Group B` yields no selected teams

**Comment by wurstbrot** [comment]
@ptechofficial @0x41head please check

**Comment by vbakke** [comment]
I've published a pull request #346, that fixes the spaces, and a few other minor, but related issues:

* Space in team names, and team groups now work
* Removed unnecessary loop in toggleTeamGroupSelection()
* Fixed: Filter chips are now initialized after teams have been loaded (no longer just a 100ms delay)
* Fixed: Incorrect background color on hover over 
* Fixed: Team filter initializes with `selected` color (in sync with the 'All' group)
