### ISSUE TITLE
Markdown everywhere

### ISSUE THREAD

**Issue by ioggstream** [devsecopsmaturitymodel/DevSecOps-MaturityModel#38]
## I wish

- the yaml content use markdown instead of html

## Instead

- it uses both html and markdown
- markdown fields have different name

## Note

if you are interested, I might help in PR
While this is a "breaking" change, it would make the yamls more maintainable and more rich of information

**Comment by wurstbrot** [comment]
We discussed this in https://github.com/wurstbrot/DevSecOps-MaturityModel/issues/35

Shall we have a call to make a plan and devide work?

**Comment by ioggstream** [comment]
Let's call!

**Comment by wurstbrot** [comment]
I created an appointment.

**Comment by ioggstream** [comment]
#71 provides an example of using .md everywhere: for now it only applies to `implementations`

**Comment by ioggstream** [comment]
I created a normalization script to convert all HTML to markdown. After #79 we could do it, wdyt?

**Comment by wurstbrot** [comment]
implemented
