### ISSUE TITLE
Consider further references 

### ISSUE THREAD

**Issue by ioggstream** [devsecopsmaturitymodel/DevSecOps-MaturityModel#49]
## Further references to be considered

- [ ] [NIST SP 800-63-3](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63-3.pdf)
- [ ] https://csrc.nist.gov/projects/cyber-supply-chain-risk-management

**Comment by wurstbrot** [comment]
To add references is a commitment for further actions, also. But in case a reference is not there for new actions, I think it is acceptable to have new actions without a specific reference, e.g. to NIST SP 800 63 3.
