### ISSUE TITLE
ISMS Ready via ISO Ordering

### ISSUE THREAD

**Issue by wurstbrot** [devsecopsmaturitymodel/DevSecOps-MaturityModel#55]
As an ISO 2700X auditor I want to see all controls for a specific domain.
Therefore, the given ordering is not sufficient and needs to be re-worked.

@ioggstream

**Comment by ioggstream** [comment]
If you make a couple of examples / screenshot I can see if this needs to be addressed in the schema files.

**Comment by wurstbrot** [comment]
Examples are in https://github.com/wurstbrot/DevSecOps-MaturityModel/issues/56
