### ISSUE TITLE
Consider using a database instead of flat file system

### ISSUE THREAD

**Issue by AndreBaumeier** [devsecopsmaturitymodel/DevSecOps-MaturityModel#60]
I am seeing more and more issues around referencing controls, actions and risks. instead of further relying on a flat file system I suggest using a relational database. Doctrine would be able to target multiple database types. Using sqlite as a default would offer the possibility to still operate the application without a database server.

**Comment by AndreBaumeier** [comment]
This could make solving these issues:

- #35
- #39
- #52
- #55

**Comment by ioggstream** [comment]
@AndreBaumeier the easy way is to create a wrapper around all data access objects and - as you say - implement a "driver" class.
 My latest patches all go in this direction but before using a database I think we should focus on the model.

Once it's done, I think a new Single Page application can be done (eg. managing tables via js frameworks, which will take care of sorting, filtering & co on front-end side). This will be tied to a REST API around objects.

My goal for now is to refine objects.
