### ISSUE TITLE
Source Composition Analysis

### ISSUE THREAD

**Issue by derweiser** [devsecopsmaturitymodel/DevSecOps-MaturityModel#94]
Hey, great work by the way. 
My issue is around testing 3rd party libraries and relates to SAMM v2 practice I-SB-1/2/3-B (Software Dependencies). DSOMM calls out this area here "Static depth for applications: Static analysis for all components/libraries" however, this is a level 4 maturity. With supply chain attacks should SCA testing have its own Test and Verification sub-dimension for SCA? Specifically tools like Dependency Check/Snyk etc. at a low maturity level up to capturing full SBOMs, using CycloneDX/Dependency Track, at a higher maturity?

thanks for consideration
Nathan

**Comment by james-ahearn** [comment]
@wurstbrot I see something along the lines of 


1. Software bill of materials is produced and Maintained. 

2. Software is checked for vulnerabilities in software components and packages. Software components are check for license violations.

3. Automated patching/PR and updates of software components an example Dependabot.
